---
title: "203 Project"
output:
  pdf_document: default
  html_document: default
date: "2026-03-29"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readxl)
library(dplyr)
library(lmtest)
library(sandwich)
library(ggplot2)
library(modelsummary)
library(tidyr)

df <- read_excel('../data/203_projectdata.xlsx', sheet = '2022')

# check missing GDP per capita
sum(is.na(df$gdp_pcap))

# drop missing rows

df_clean <- df %>%
  filter(!is.na(gdp_pcap))

# check missing rows again
sum(is.na(df_clean$gdp_pcap))
sum(is.na(df_clean$lex))

```

### Base model Life expectancy vs. GDP per capita
```{r}
model_base <- lm(lex ~ gdp_pcap, data = df_clean)
summary(model_base)
```

```{r}
# Use robust standard errors.
robust_se_base <- sqrt(diag(vcovHC(model_base, type = "HC1")))

coeftest(model_base, vcov = vcovHC(model_base, type = "HC1"))
```

### Check for skewness in distribution of gdp per capita.
```{r}
ggplot(df_clean, aes(x = gdp_pcap)) +
  geom_histogram(bins = 30) +
  labs(
    title = "Distribution of GDP per Capita",
    x = "GDP per Capita",
    y = "Count"
  )
ggplot(df_clean, aes(x = log(gdp_pcap))) +
  geom_histogram(bins = 30) +
  labs(
    title = "Distribution of Log GDP per Capita",
    x = "Log GDP per Capita",
    y = "Count"
  )
```
```{r}
par(mfrow = c(1, 2))

hist(df_clean$gdp_pcap, main = "GDP per Capita", xlab = "GDP")
hist(log(df_clean$gdp_pcap), main = "Log GDP per Capita", xlab = "Log GDP")
```

### High correlation between gdp per capita and average daily income. Exclude the latter variable.
```{r}
cor(df_clean$gdp_pcap, df_clean$average_daily_income, use = "complete.obs")
cor(log(df_clean$gdp_pcap), df_clean$average_daily_income, use = "complete.obs")
cor(log(df_clean$gdp_pcap), log(df_clean$average_daily_income), use = "complete.obs")

# Plot gdp per capita vs average daily income.
ggplot(df_clean, aes(x = gdp_pcap, y = average_daily_income)) +
  geom_point(alpha = 0.5) +
  scale_x_log10() +
  scale_y_log10() +
  labs(
    x = "GDP per Capita",
    y = "Average Daily Income",
    title = "GDP vs Income"
  )
```


```{r}
model_log <- lm(lex ~ log(gdp_pcap), data = df_clean)
summary(model_log)
```


```{r}
# Use robust standard errors.
robust_se_log <- sqrt(diag(vcovHC(model_log, type = "HC1")))

coeftest(model_log, vcov = vcovHC(model_log, type = "HC1"))
```

### Add demographic additional variables.
```{r}
model_3 <- lm(
  lex ~ log(gdp_pcap) +
    children_per_woman_total_fertil +
    median_age_years,
    data = df_clean
)

summary(model_3)
anova(model_log, model_3)
```

```{r}
# Use robust standard errors.
coeftest(model_3, vcov = vcovHC(model_3, type = "HC1"))
```

### Add inequality additional variables.
```{r}
model_4 <- lm(
  lex ~ log(gdp_pcap) +
    children_per_woman_total_fertil +
    median_age_years +
    gini +
    population_density_per_square_k,
    data = df_clean
)

summary(model_4)
anova(model_3, model_4)
```

```{r}
# Use robust standard errors.
coeftest(model_4, vcov = vcovHC(model_4, type = "HC1"))
```


```{r}
model_5 <- lm(
  lex ~ log(gdp_pcap) +
    children_per_woman_total_fertil +
    median_age_years +
    gini +
    log(population_density_per_square_k),
    data = df_clean
)

summary(model_5)
```

```{r}
# Use robust standard errors.
coeftest(model_5, vcov = vcovHC(model_5, type = "HC1"))
```

### Add Tech/Infrastructure additional variables.
```{r}
model_6 <- lm(
  lex ~ log(gdp_pcap) +
    children_per_woman_total_fertil +
    median_age_years +
    gini +
    log(population_density_per_square_k) +
    cell_phones_per_100_people +
    broadband_subscribers_per_100_p +
    co2_pcap_cons,
    data = df_clean
)

summary(model_6)
```

```{r}
modelsummary(
  list(
    "Baseline" = model_base,
    "Log GDP" = model_log,
    "Demographics" = model_3,
    "Final Model" = model_5
  ),
  vcov = "HC1",
  stars = TRUE,
  title = "Regression Models of Life Expectancy",
  statistic = "({std.error})",
  gof_omit = "AIC|BIC|Log.Lik|RMSE|F",
  coef_map = c(
    "gdp_pcap" = "GDP per Capita",
    "log(gdp_pcap)" = "Log GDP per Capita",
    "children_per_woman_total_fertil" = "Children per Woman",
    "log(population_density_per_square_k)" = "Log Population Density",
    "median_age_years" = "Median Age",
    "gini" = "Gini Index"
  )
)
```






